[general]
live_config_reload = true
import = [
    #"~/.local/share/nvim/site/pack/paqs/start/modus-themes.nvim/extras/alacritty/modus_operandi.toml"
    "~/.local/share/nvim/site/pack/paqs/start/modus-themes.nvim/extras/alacritty/modus_operandi_tinted.toml"

    #"~/.local/share/nvim/site/pack/paqs/start/modus-themes.nvim/extras/alacritty/modus_vivendi.toml"
    #"~/.local/share/nvim/site/pack/paqs/start/modus-themes.nvim/extras/alacritty/modus_vivendi_tinted.toml"
]

[window]
decorations = "None"
startup_mode = "Maximized"

[font]
size = 14.0
normal = { family = "Cascadia Code NF" }

[terminal]
shell = { program = "tmux", args = ["new", "-As", "main"] }

[selection]
save_to_clipboard = true

[scrolling]
multiplier = 0 # disable mouse wheel

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
