[general]
live_config_reload = true
import = [
    #"~/.local/share/nvim/site/pack/paqs/start/modus-themes.nvim/extras/alacritty/modus_operandi.toml"
    "~/.local/share/nvim/site/pack/paqs/start/modus-themes.nvim/extras/alacritty/modus_vivendi.toml"
]

[window]
decorations = "None"
startup_mode = "Maximized"

[font]
size = 16.0

[font.normal]
family = "Fantasque Sans Mono"
style = "Regular"
# fc-list : family style | grep -i fanta
# family = "Agave"
# family = "Cascadia Code"
# family = "Fantasque Sans Mono"
# family = "Fira Code"
# family = "Hasklig"
# family = "Inconsolata"
# family = "Iosevka Term"
# family = "JetBrains Mono"
# family = "PragmataPro"
# family = "PT Mono"
# family = "Roboto Mono"
# family = "SF Mono"

[font.italic]
family = "Fantasque Sans Mono"
style = "Italic"

[font.bold]
family = "Fantasque Sans Mono"
style = "Bold"

[font.bold_italic]
family = "Fantasque Sans Mono"
style = "Bold Italic"

[terminal]
shell = { program = "tmux", args = ["new", "-As", "main"] }

[selection]
save_to_clipboard = true

[scrolling]
multiplier = 0 # disable mouse wheel

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
